### ISSUE TITLE
alternative currencies were previously supported... weren't they?

### ISSUE THREAD

**Issue by pironic** [brianberg/ha-nicehash#3]
I had the configuration working fine, upgraded to latest and now I can't view my sensors in CAD currency. This suggests to me that the only thing preventing alternative currencies is a check in the python of this plugin? Can you add support for additional currencies?
https://github.com/brianberg/ha-nicehash/blob/master/custom_components/nicehash/sensor.py#L124

Am I crazy to think it worked before? I checked the history on the code and didn't see any recent changes to it... 

## Version of the custom_component

72543f6

## Configuration

```yaml

nicehash:
  organization_id: !secret nicehash_id
  api_key: !secret nicehash_key
  api_secret: !secret nicehash_secret
  currency: CAD # (default = USD)
  balances: true # (default = false) - Enable balance sensors
  rigs: true # (default = false) - Enable rig sensors
  devices: false # (default = false) - Enable device sensors
  payouts: false # (default = false) - Enable payout sensors

```

## Describe the bug

Should be able to support any currency that nicehash also supports.

## Debug log

```text

Logger: custom_components.nicehash.sensor
Source: custom_components/nicehash/sensor.py:151
Integration: NiceHash (documentation, issues)
First occurred: 10:48:29 (1 occurrences)
Last logged: 10:48:29

Invalid currency: must be EUR or USD

```
